# Site settings
title: OpaaliAPI Blog
header-img: img/blog_logo-main_1600x500.jpg
email: jukka-pekka.lasanen@helsinki.fi
description: "A Blog about... (nothing)"
# url: "http://yourdomain.com"
# email_username:  
email_support: jukka-pekka.lasanen@helsinki.fi
opaali_tuki: jukka-pekka.lasanen@helsinki.fi
opaali_portal: "http://www.helsinki.fi"
opaali_forum: "http://www.helsinki.fi"

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

avatar: img/OpaaliPortal.jpg

